### ISSUE TITLE
Scoreboard number not showing on tab menu

### ISSUE THREAD

**Issue by SiroQ** [FlawlessNick/FlawlessNick#2]
Vanilla:
![screenshot_2](https://user-images.githubusercontent.com/26434739/38179256-027a9d28-365c-11e8-8a88-9540b73e53e5.png)
Modded:
![screenshot_1](https://user-images.githubusercontent.com/26434739/38179291-75158fbe-365c-11e8-8fd3-a373266e9247.png)

**Comment by SimplyRin** [comment]
なおりました()
